services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: services
      POSTGRES_DB: drgest
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL: postgresql://sa:services@postgres:5432/drgest
    depends_on:
      - postgres
    labels:
      - traefik.enable=true
      - traefik.http.routers.drgest.rule=Host(`drgest.app`)
      - traefik.http.routers.drgest.entrypoints=websecure
      - traefik.http.routers.drgest.tls.certresolver=letsencrypt
      - traefik.http.services.drgest.loadbalancer.server.port=3000
      - traefik.docker.network=app_default
    restart: unless-stopped

volumes:
  postgres_data: