services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: services
      POSTGRES_DB: drgest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sa"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build: .
    container_name: nextjs_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://sa:services@postgres:5432/drgest
    depends_on:
      postgres:
        condition: service_healthy

    labels:
      - traefik.enable=true
      - traefik.http.routers.drgest.rule=Host(`drgest.app`)
      - traefik.http.routers.drgest.entrypoints=websecure
      - traefik.http.routers.drgest.tls.certresolver=letsencrypt
      - traefik.http.services.drgest.loadbalancer.server.port=3000
      - traefik.docker.network=traefik-proxy

    restart: unless-stopped

    networks:
      - traefik-proxy
      - app-internal

volumes:
  postgres_data:

networks:
  traefik-proxy:
    external: true
  app-internal:
    driver: bridge